### ISSUE TITLE
slack ignores branch option

### ISSUE THREAD

**Issue by snowiow** [deployphp/recipes#109]
Hi, the main deployer recipes like [update_code.php](https://github.com/deployphp/deployer/blob/master/recipe/deploy/update_code.php#L19) are also checking if the branch option is set. Is there a reason why the option is ignored in the slack recipe? Otherwise I would like to do a PR for this. Thanks in advance 🙂

**Comment by elfet** [comment]
No, pr will be good 🙂 
Also refactoring of slack recipe will be awesome 👍🏻

**Comment by snowiow** [comment]
Hi, which things do you want to refactor in the slack recipe? Maybe I can help you with that.

**Comment by elfet** [comment]
Make it more BEAutiful 🌈

😆
