### ISSUE TITLE
__DIR__ does not return working directory

### ISSUE THREAD

**Issue by rayphi** [deployphp/recipes#112]
>Magic constants `__DIR__`
The directory of the file. If used inside an include, the directory of the included file is returned. This is equivalent to dirname(`__FILE__`). This directory name does not have a trailing slash unless it is the root directory.

https://github.com/deployphp/recipes/blob/master/configure.php#L50

`__DIR__` should be replaced by `getcwd()` wich returns the working directory.

**Comment by elfet** [comment]
Done.

**Comment by Lukash82** [comment]
Please create tag with this fix https://github.com/deployphp/recipes/blob/master/configure.php#L50
Now this recipe works only in the master branch

**Comment by antonmedv** [comment]
Done.
