### ISSUE TITLE
Slack recipe depends on the project being present

### ISSUE THREAD

**Issue by Lambik** [deployphp/recipes#116]
Hi,

I'm deploying the project from a server that contains only the deploy.php file, with the vendor folder. It does not have the entire project with its .git folder there, because it's not needed in our setup.

However, in that case, the slack recipe fails, because it reads data using `git` (like branch, user, revision and so on). I'm fine with not having that information in the slack message (just "deployed to stage xyz" is fine).

Could you make that information gathering optional somehow? Thanks!

**Comment by antonmedv** [comment]
Will try to do it, for now you can use Slack API directly.

**Comment by hslatman** [comment]
Furthermore, shouldn't this run remotely? Right now the printed revision is based on the branch that is checked out locally. There's no guarantee that this is always the branch you're deploying remotely.

**Comment by antonmedv** [comment]
@hslatman i'm agree.
