### ISSUE TITLE
How to migrate from capistrano 2.x or 3.x to deployphp?

### ISSUE THREAD

**Issue by uran1980** [deployphp/recipes#13]
Hi, is there any how-to docs? Thanks.

**Comment by gordalina** [comment]
Hi @uran1980, this is a recipes repository for deployer, It would be best to open an issue on deployphp/deployer

**Comment by ZeeCoder** [comment]
I like the idea @uran1980, so please do reopen this issue in the deployer repository. :)

**Comment by webdevilopers** [comment]
Have you opened a new issue @uran1980 ? Can you please link it? Thanks!

**Comment by webdevilopers** [comment]
Ah, there we have it: https://github.com/deployphp/deployer/issues/359
