### ISSUE TITLE
Rollbar recipe

### ISSUE THREAD

**Issue by adriandmitroca** [deployphp/recipes#154]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Recipes Version   | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

Rollbar's recipe would need some improvements due to their official documentation, which says:
- `rollbar_username` is optional param, but required in Deployer. It requires totally useless & hardcoded data for every person in the project. This should be an optional parameter in Deployer too.
- `comment` which is also optional, but Deployer forces default value such as ```_{{user}}_ deploying `{{branch}}` to *{{target}}*``` which is also totally useless and duplicates content in Rollbar panel. This parameter should be empty by default and optional.

What do you think?

**Comment by antonmedv** [comment]
I think it's okay. If you can send a PR with screen shots of improvements  will be really cool.

**Comment by razseo** [comment]
About username - on my server when use deploy from console it's works:
`set('user', isset($_SERVER['USER']) ? $_SERVER['USER'] : 'unknown');`
