### ISSUE TITLE
Combine phar installation with recipes

### ISSUE THREAD

**Issue by Konafets** [deployphp/recipes#155]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.0.3
| Recipes Version   | 6.0
| Local Machine OS  | OSX
| Remote Machine OS | Linux

### Description 
I installed Deployer as described [here](https://deployer.org/docs/installation#download-phar-archive). Now I need the NPM recipe, which I installed via composer require to the project and require it in the deploy.php

### Content of `deploy.php`
```php
require 'recipe/typo3.php';
require 'recipe/npm.php';

...

after('deploy:update_code', 'npm:install');
```

### Output log
```
Warning: require(recipe/npm.php): failed to open stream: No such file or directory in /Users/$user/Sites/example.com/dev/deploy.php on line 5

Call Stack:
    0.0007     364416   1. {main}() /usr/local/bin/dep:0
    0.0140     541544   2. require('phar:///usr/local/bin/dep/bin/dep') /usr/local/bin/dep:4
    0.0230    1354504   3. Deployer\Deployer::run() phar:///usr/local/bin/dep/bin/dep:119
    0.0362    2341184   4. call_user_func:{phar:///usr/local/bin/dep/src/Deployer.php:319}() phar:///usr/local/bin/dep/src/Deployer.php:319
    0.0362    2341184   5. Deployer\Deployer::Deployer\{closure}() phar:///usr/local/bin/dep/src/Deployer.php:319
    0.0432    2351440   6. require('/Users/$user/Sites/example.com/dev/deploy.php') phar:///usr/local/bin/dep/src/Deployer.php:318
```

How can I get this to work?

**Comment by antonmedv** [comment]
Yes, this is an issue for now. Will solve it in future release.
Now you can use full path to recipe: `vendor/deployer/recipes/recipe/*.php`

**Comment by razseo** [comment]
Solution:
1. Go to /usr/share/php (By default it's in include_path)
2. Create file /usr/share/php/ext_include.php
`<?php
        require dirname (__FILE__) . '/vendor/autoload.php';
?>
`
3. Install recipes by composer
4. Open your deploy file and insert this after "namespace Deployer;"
`require 'ext_include.php';`

After this my dep script works with recipes.
