### ISSUE TITLE
slack:notify:failure

### ISSUE THREAD

**Issue by joepsyko** [deployphp/recipes#158]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.0.3
| Recipes Version   | 6.0.1
| Local Machine OS  | OSX
| Remote Machine OS | Linux

### Description 
Could be possible to include a slack notification for deployment error?

**Comment by antonmedv** [comment]
Yes, PR are welcome.

**Comment by joepsyko** [comment]
Done, hope I did it correct.
