### ISSUE TITLE
Can't set channel for Slack recipe?

### ISSUE THREAD

**Issue by gavinhewitt** [deployphp/recipes#160]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question

### Description 
Looking at older versions of the Slack recipe you could set channel and custom title etc, but they seem to be removed. Am I missing something?

**Comment by antonmedv** [comment]
Maybe, I refactored it a lot. What you are trying to achieve?

**Comment by gavinhewitt** [comment]
I'd like to set the standard stuff like icon, title etc, but most importantly I'd like to be able to specify the channel. Now a notification just goes to (I think) the first channel it encounters.

**Comment by antonmedv** [comment]
Now slack recipe uses new slack's integration which allows you to setup channel. Click Add to Slack button and you will see.

**Comment by gavinhewitt** [comment]
Ah, I saw the button but it was entirely clear what would happen. All clear now, thanks!

**Comment by gavinhewitt** [comment]
Ah, I saw the button but it was not entirely clear (to me at least) what would happen. All clear now, thanks!
