### ISSUE TITLE
Telegram undefined variable

### ISSUE THREAD

**Issue by ideea** [deployphp/recipes#170]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | N/A
| Recipes Version   | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
*If you're reporting a bug, please include following information*
Dunno who wrote this, but it should be fixed: 
HP Notice:  Undefined variable: TELEGRAM_TOKEN_HERE in /Users/ideea/Development/www/areto/tjenestetorget/tjenestetorget_v2/vendor/deployer/recipes/recipe/telegram.php on line 21

Notice: Undefined variable: TELEGRAM_TOKEN_HERE in /XXX/vendor/deployer/recipes/recipe/telegram.php on line 21
PHP Notice:  Undefined variable: TELEGRAM_CHATID_HERE in /XXX/vendor/deployer/recipes/recipe/telegram.php on line 22

Notice: Undefined variable: TELEGRAM_CHATID_HERE in /XXX/vendor/deployer/recipes/recipe/telegram.php on line 22
### Content of `deploy.php`
```php
CONTENT
```

### Output log
*With enabled option for verbose output `-vvv`.*

**Comment by naffiq** [comment]
@antonmedv 

I think this issue should be closed now 😃
