### ISSUE TITLE
Rsync recipe doesn't use SSH multiplexing

### ISSUE THREAD

**Issue by mikeymike** [deployphp/recipes#171]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | ^6
| Recipes Version   | ^6
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Rsync reciple does not take ssh multiplexing into account. 

### Steps to reproduce
Configure a multiplexing deployment with rsync recipe. Using verbose output you will be able to see that the ssh command does not use `ControlPath`

### Content of `deploy.php`
Will attempt to supply if required, just tricky to pull out atm

### Output log
Will attempt to supply if required, just tricky to pull out atm

--- 

I'm not entirely sure if this should be resolved here, I've previously overwrote the rsync task to include the multiplexing options but I feel that maybe the sshArguments object pulled from the host should also have the multiplexing configuration applied to it, so potentially a bug in deployer package instead.

I'm happy to look at putting together a PR to fix this given some consensus on where the fix should be

**Comment by antonmedv** [comment]
Need to get deeper. Maybe sshArguments and multiplexing should be putter to arg rsync.

**Comment by mikeymike** [comment]
I think it's odd to pull the ssh arguments from the host and not have the multiplexing details there if it's enabled, I helped refactor some of that before so I think I can help out refactor that bit a little further

I'll take a look today to see if I can find the best approach
