### ISSUE TITLE
Telegram fail report task

### ISSUE THREAD

**Issue by naffiq** [deployphp/recipes#174]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Recipes Version   | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Telegram recipe needs fail report and documentation for this feature.

**Comment by asafov** [comment]
Done. PR #207

**Comment by naffiq** [comment]
@asafov that's great, thank you!
