### ISSUE TITLE
Posting multiple messages using recipes is currently impossible

### ISSUE THREAD

**Issue by stokjes** [deployphp/recipes#179]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6+
| Recipes Version   | 6+
| Local Machine OS  | OSX
| Remote Machine OS | Vagrant/centos6

### Description 
Currently all recipes don't have the possibility to post/send multiple requests to 3rd party libraries. This is because:

* Once() is used in the recipes;
* Recipes don't handle array values;

### Question
Why is that? The recipe i'm currently using is Slack and I want to post deployer messages to two channels. I can fork the recipe and allow an array value to be distributed but all other recipes don't work this way. I can refactor the recipe in my own project and allow this change but future upgrades will then be impossible.

What are your thoughts on this?

**Comment by antonmedv** [comment]
Recipes implements only most common usage case. Don't try to fit all possible need. But in deployer you can simple override any stuff. Or just implement your own recipe. I think this is better approach for common recipes.

**Comment by stokjes** [comment]
After discussions with our team we will stick with one release channel for now, so the question has been resolved.
