### ISSUE TITLE
Several issues in discord

### ISSUE THREAD

**Issue by chapterjason** [deployphp/recipes#181]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.2
| Recipes Version   | 6.1
| Local Machine OS  | Ubuntu 17.10
| Remote Machine OS | Debian GNU/Linux 8 (jessie)

### Description 
I'll just want to notify you that in the Discord recipe the `namespace Deployer;` statement is missing. Without that it comes to this error `[Error] Call to undefined function set()    `. I think there was also some API changes? The callback gets called once cause of config cache for callbacks result? And the placeholders in the array doesn't got replaced.

### Solution
I edited the discord file and came to the following solution. This solution fix all the above issues.
```php
<?php
/* (c) Lucas Mezêncio <lucas.mezencio@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Deployer;

use Deployer\Task\Context;
use Deployer\Utility\Httpie;

set('discord_webhook', function () {
    return 'https://discordapp.com/api/webhooks/{{discord_channel}}/{{discord_token}}/slack';
});

// Deploy messages
set('discord_notify_text', ':information_source: **{{user}}** is deploying branch `{{branch}}` to _{{target}}_');
set('discord_success_text', ':white_check_mark: Branch `{{branch}}` deployed to _{{target}}_ successfully');
set('discord_failure_text', ':no_entry_sign: Branch `{{branch}}` has failed to deploy to _{{target}}_');

set('discord_type', 'discord_notify_text');

// Helpers
task('discord_send_message', function(){
    Httpie::post(get('discord_webhook'))->body(['text' => get(get('discord_type'))])->send();
});

// Tasks
desc('Just notify your Discord channel with all messages, without deploying');
task('discord:test', function () {
    set('discord_type', 'discord_notify_text');
    invoke('discord_send_message');
    set('discord_type', 'discord_success_text');
    invoke('discord_send_message');
    set('discord_type', 'discord_failure_text');
    invoke('discord_send_message');
})
    ->once()
    ->shallow();

desc('Notify Discord');
task('discord:notify', function () {
    set('discord_type', 'discord_notify_text');
    invoke('discord_send_message');
})
    ->once()
    ->shallow()
    ->isPrivate();

desc('Notify Discord about deploy finish');
task('discord:notify:success', function () {
    set('discord_type', 'discord_success_text');
    invoke('discord_send_message');
})
    ->once()
    ->shallow()
    ->isPrivate();

desc('Notify Discord about deploy failure');
task('discord:notify:failure', function () {
    set('discord_type', 'discord_failure_text');
    invoke('discord_send_message');
})
    ->once()
    ->shallow()
    ->isPrivate();

```

**Comment by antonmedv** [comment]
Thanks! Fixed in 4b66561afe0e48c8c85b0865bb61494f20f0fb1c

**Comment by chapterjason** [comment]
@antonmedv As I mentioned there are some more bugs.

Cause of the option cache for configuration (https://github.com/deployphp/deployer/blob/master/src/Configuration/Configuration.php#L87) the callback can‘t be executed. They don’t receive the argument that is given here https://github.com/deployphp/recipes/blob/master/recipe/discord.php#L34 

 I also receive messages without the replacement of the placeholders. That comes from here https://github.com/deployphp/deployer/blob/master/src/Configuration/Configuration.php#L120 cause parse of arrays isn’t implemented.

**Comment by antonmedv** [comment]
Can you send PR to fix it?

**Comment by chapterjason** [comment]
@antonmedv sure, what do you think about the solution I posted above? Are there any other ways ?
