### ISSUE TITLE
[Error] Call to undefined method Symfony\Component\Console\Helper\QuestionHelper::getInputStream()

### ISSUE THREAD

**Issue by hulupiao** [deployphp/recipes#202]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | 6.3.0
| Recipes Version   | ^6.1
| Local Machine OS  | MacOS Mojave
| Remote Machine OS | ubuntu18

### Description 
$ dep --file=./.ci/deployer/deploy.php config:hosts Test -vvv

                                                                                                                        
 [Error] Call to undefined method Symfony\Component\Console\Helper\QuestionHelper::getInputStream()                     
                                                                                                                        

 #0 phar:///usr/local/bin/dep/vendor/symfony/console/Application.php(145):                                              
 Symfony\Component\Console\Application->configureIO(Object(Symfony\Component\Console\Input\ArgvInput),                  
 Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                
 #1 phar:///usr/local/bin/dep/src/Deployer.php(331):                                                                    
 Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput),                          
 Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                
 #2 phar:///usr/local/bin/dep/bin/dep(119): Deployer\Deployer::run('6.3.0', '/data/www/ret/a...')                       
 #3 /usr/local/bin/dep(4): require('phar:///usr/loc...')                                                                
 #4 {main}  

### Content of `deploy.php`
```php
CONTENT
```
<?php
namespace Deployer;

use Symfony\Component\Console\Helper\QuestionHelper;

$composerHome = getenv("COMPOSER_HOME") ?: getenv("HOME") . '/.composer/';
include $composerHome . '/vendor/autoload.php';

require 'recipe/laravel.php';
require 'recipe/rsync.php';

$workSpace = realpath(dirname(__FILE__) . "/../../");
$cwd       = realpath(dirname(__FILE__)) . '/';

chdir($workSpace);
### Output log
*With enabled option for verbose output `-vvv`.*
$php -v
PHP 7.2.11

**Comment by antonmedv** [comment]
What is symfony console version?

**Comment by hulupiao** [comment]
> What is symfony console version?

cat ~/.composer/vendor/symfony/console/CHANGELOG.md
CHANGELOG
=========

4.1.0

**Comment by mediact-pipelines** [comment]
FYI, I ran into a similar issue today
I have both Deployer (v6.4.3) and Deployer recipes (6.2.1) installed (globally)
Deployer requires ` "symfony/console": "~2.7|~3.0|~4.0"`
As a result `symfony/console:4.2.0` gets installed and my recipe fails on calling `dep` with
```
 [Error] Call to undefined method Symfony\Component\Console\Helper\QuestionHelper::getInputStream()  
```
If I manually require `symfony/console:^3` (which results in installing v3.4.21) I can use my recipe again.
Have not found the root-cause yet

**Comment by johnny-bit** [comment]
According to `symfony/console` changelog @ https://github.com/symfony/console/blob/master/CHANGELOG.md getInputStream was removed in v 4.0.0
