### ISSUE TITLE
What about merging recipes and deployer?

### ISSUE THREAD

**Issue by antonmedv** [deployphp/recipes#208]
subj

**Comment by asafov** [comment]
I think it will be better for project. BTW - what about Deployer CI (Pro)? It's stopped?

**Comment by johnny-bit** [comment]
Sounds good. I think having main recipes + contrib was not as intuitive as it could be and release pace of both do match.

**Comment by antonmedv** [comment]
@asafov development is continuing :) it's really big projects and have a lot of difficult parts, but I'm working on it. As well on new deployer v7, docker support, new website + new docs. So I hope to ship it soon, but dont know when.

**Comment by asafov** [comment]
@antonmedv на самом деле у меня уже была идея сделать что-то типа конфигуратора с веб-мордой для cli деплойера. У меня есть каркас для CRUD, который я могу быстро развернуть, дальше останется только загнать туда все модули.
Идея была сделать возможность прямо из морды конфигурировать в том числе и flow. У тебя такого же рода продукт получается?

Translate: i developed now web interface for deployer for own needs.

**Comment by antonmedv** [comment]
@asafov can you show your web interface?

**Comment by asafov** [comment]
https://ibb.co/nrdmMkg
For example. Builded from db properties. ACL, auth, data tables, filters, fields for edit (with types), etc.
Based on ZF2. I have idea for run deployer by gearman or any other technology and build config at the fly from databases. Arch was "Host" -> "Code base" -> "Application".
"Code base" - is unique product (by git), application is Host + Code Base + Settings.
