### ISSUE TITLE
[slack] No branch or commit name

### ISSUE THREAD

**Issue by andrey-helldar** [deployphp/recipes#215]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.4.3
| Recipes Version   | 6.2.1
| Local Machine OS  | windows 10
| Remote Machine OS | centos 7 on production and ubuntu 18 on deployment

### Description 
In the sent message in the slak there is no name of the branch or commit

### Steps to reproduce
```bash
php artisan deploy --revision=$CI_COMMIT_SHA
```

![photo_2019-02-22_09-54-36](https://user-images.githubusercontent.com/10347617/53225138-19ee2380-3688-11e9-88e2-18a245a93fd6.jpg)

**Comment by pedroresende** [comment]
exactly the same problem with `--tag`

**Comment by pedroresende** [comment]
@andrey-helldar found a work around for this. In your deploy.php file, add the following

```php
set('revision', function() {
    return runLocally('git rev-parse HEAD');
});
set('slack_text', 'Deploying `{{revision}}` to *{{stage}}*');
```
for the case of the tag,

```php
set('tag', function() {
    return runLocally('git describe --tags');
});
set('slack_text', 'Deploying `{{tag}}` to *{{stage}}*');
```
