### ISSUE TITLE
RocketChat Integration

### ISSUE THREAD

**Issue by Baachi** [deployphp/recipes#225]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question, Feature Request
| Deployer Version  | N/A
| Recipes Version   | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

Hey guys!

i recently build a [recipe](https://github.com/Baachi/deployer-rocketchat) for [rocketchat](https://rocket.chat/), because we use this internally in our company. 

I think it would be nice to have this recipe in the official repository. Would you accept a PR?

**Comment by antonmedv** [comment]
Will be cool.

**Comment by Baachi** [comment]
Closed.
