### ISSUE TITLE
Sentry Release/Deploy fails due to server response

### ISSUE THREAD

**Issue by MarnuLombard** [deployphp/recipes#235]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.3
| Recipes Version   | 6.13
| Local Machine OS  | MacOS Mojave 10.14.6
| Remote Machine OS | Debian Stretch 9.9

Specifically related to `recipes/sentry.php`
So I'm pinging @Gamesh and @antonmedv 
As they seem to be the maintainers there.

### Description 
In the second part of the `deploy:sentry` task, when it creates the `deploy` it fails, as there is no `id` in the json response from the server.
The block of code that triggers the error is:
```php
if (!isset($response['id'], $response['environment'])) {
    throw new \RuntimeException(sprintf('Unable to create a deployment: %s', print_r($response, true)));
} 
```

The response I get from my server is:
```json
{
  "dateFinished": "2019-08-22T09:40:47Z",
  "dateStarted": "2019-08-22T09:40:47Z",
  "environment": "prod",
  "name": "lonely_fermat",
  "url": "https://example.com/"
}
```

**My sentry server is self-hosted. Version 8.17.0**

### Content of `deploy.php`
```php
// ...
set('sentry', [
    'organization' => 'sentry',
    'projects' => [
        'example',
    ],
    'token' => '[REDACTED]',
    // get a short sha of current HEAD
    'version' => exec('git rev-parse --short HEAD'),
    // Sentry requires format of YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z]
    'date_released' => date('c'),
    'sentry_server' => 'https://sentry.example.com',
    'url' => 'https://example.com/',
    'deploy_name' => exec('curl -s https://frightanic.com/goodies_content/docker-names.php'),
]);
// ...
```

**Comment by Gamesh** [comment]
hmm, hard to tell, most likely your self-hosted sentry is out of date with sentry service. For other people and me included it works with hosted one. You could try using an older version of this recipe maybe that will work

**Comment by MarnuLombard** [comment]
Okay cool. I'll update my server instance to 9.0 and give feedback here

**Comment by Gamesh** [comment]
> The current version of the web API is known as v0 and is considered to be in a draft phase. While we don’t expect public endpoints to change greatly, keep in mind that the API is still under development.

it seems there is no way to negotiate api version and it still in flux

**Comment by MarnuLombard** [comment]
I see.
It's possible that you drop the check for `$response['id']` and the false negatives on successful deploys will go away.

However, I have upgraded to version 9.1.2 and the error no longer comes up  - so I'm going to close this issue.

Thank you for getting back to me so quickly.
