### ISSUE TITLE
Catch-22: Deployer installs composer dependencies, but deployer/recipes is a dependency

### ISSUE THREAD

**Issue by sandermarechal** [deployphp/recipes#246]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.6.0
| Recipes Version   | 6.2.2
| Local Machine OS  | Linux
| Remote Machine OS | Linux

### Description 
Using these recipes in a CI/CD pipeline results in a catch-22. Deployer runs composer install (which installs these recipes) but deployer cannot run until the recipes are installed.

Also, in CI/CD de require-dev dependencies are not installed so I would need to add deployer/recipes to de "require" section instead of "require-dev".

I have deployer installed as a global .phar file in /ust/local/bin/deployer.phar. I make a *clean* checkout of my project, then I try to run a deployer task.

### Content of `deploy.php`
```php
<?php

namespace Deployer;

require 'recipe/common.php';
require 'vendor/deployer/recipes/recipe/rsync.php';

// ...
```

### Output log
Warning: require(vendor/deployer/recipes/recipe/rsync.php): failed to open stream: No such file or directory in deploy.php on line 6

**Comment by sandermarechal** [comment]
My solution so far is to just copy/paste the recipe I need into my own project and drop deployer/recipes. 

It would be much better in these recipes were in the standard deployer.phar file, or if it is possible to create a custom deployer.phar file that includes these recipes.

**Comment by antonmedv** [comment]
Actually this what I'm working on: copy all recipes to the main repo under `contrib`.

**Comment by sandermarechal** [comment]
That would be great!
