### ISSUE TITLE
Zulip recipe

### ISSUE THREAD

**Issue by ezitisitis** [deployphp/recipes#249]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.x

### Description 
At company we use Zulip and starting to think that we can make an integration of Deployer in our chats. Unfortunately didn't found an Zulip recipe.

If accepted, I will start to work on it.

**Comment by johnny-bit** [comment]
Do it :) The more the merrier!
