### ISSUE TITLE
Cachetool - use env instead of set/get

### ISSUE THREAD

**Issue by mkurzeja** [deployphp/recipes#33]
I think that the cachetool recipe should use env() instead of get() to load cachetool options. It is quite likely to have different fpm settings for different servers. For example: we have fpm on our staging server listening to localhost:9001 but the production server can run on a different port or use unix sockets.

I could prepare a PR - to keep the backwards compatibility the recipe would use the env() value and fallback to the get() value.

**Comment by gordalina** [comment]
Your reasoning is good, please do prepare a PR. Thanks
