### ISSUE TITLE
recipes/slack.php: got "Call to undefined method Deployer\Server\Local::getConfiguration()" using localServer(...) 

### ISSUE THREAD

**Issue by karakum** [deployphp/recipes#39]
> PHP Fatal error:  Call to undefined method Deployer\Server\Local::getConfiguration() in .../recipes/slack.php on line 24

"Local" server implementation does not have "configuration" property.

**Comment by oanhnn** [comment]
@karakum Thank you for reporting bug.
I fixed it. Please check again.
