### ISSUE TITLE
Copy composer vendor folders

### ISSUE THREAD

**Issue by achristodoulou** [deployphp/recipes#42]
Hi,

I have created a task that checks if vendor folder exists to copy it to new release instead of downloading everything again. If you think that this is useful tell me and I ll do a pull request.

```
task('copy_vendors', function () {
    $current_vendors = env('deploy_path') . '/current/vendor';
    if(file_exists($current_vendors)) {
        run("cp -ar $current_vendors {{release_path}}");
    }
})->desc('Copy vendor folder if already exists');
```

**Comment by elfet** [comment]
Hi! How this speed ups deploys? 

Note what composer itself caching vendor, so it's does not download it every time.

**Comment by achristodoulou** [comment]
True, but when you have for example 118 packages (this is my case :))  and no one is install then composer will have to go one by one and get them from cache and that requires more time against copying the existing vendor directory and then composer installing only what is required.

```
Not copying vendor folder from current release, deployer took:
real	0m47.409s
user	0m19.889s
sys	0m5.653s

Copying vendor folder from current release, deployer took:
real	0m19.326s
user	0m12.878s
sys	0m3.183s
```

**Comment by oanhnn** [comment]
@achristodoulou 
1. If copy, when project require new package (change `composer.lock`), it wont be download.
2. In your task, `file_exists` is check on local machine, but `run` is running remote machine. :-1:

**Comment by achristodoulou** [comment]
1. During development you add a new package to your composer.json, run composer update and then commit your changes including composer.lock. When u run composer install in production it will read your packages from composer.lock correct? If so the new package will be download.
2.True I am running this on localServer

**Comment by oanhnn** [comment]
> During development you add a new package to your composer.json, run composer update and then commit your changes including composer.lock. When u run composer install in production it will read your packages from composer.lock correct? If so the new package will be download.

Your `deploy` task look like?
```php
task('deploy', [
     // ...
     'deploy:copy_vendors',
     'deploy:vendors',
     // ...
]);
```

**Comment by achristodoulou** [comment]
Yes, actually is like this.

```
before('deploy:vendors', 'copy_vendors');
```

**Comment by achristodoulou** [comment]
Anyway, the initial idea was to optimize the deployment procedure on localServer, so if by copying vendors will not do any harm I am ok with this. And as you can see in my previous post, the execution time is about half :)

**Comment by achristodoulou** [comment]
Fyi, after checking the existing recipes I found out that in common.php there is a task called "deploy:copy_dirs" which is doing the same thing as I have suggested, is just more generic.

**Comment by elfet** [comment]
Can you write a docs for it?

**Comment by achristodoulou** [comment]
Are you referring to the existing task in common.php 'deploy:copy_dirs', if that so, yes I can update doc in https://github.com/deployphp/docs/blob/master/recipes.md accordingly.

**Comment by elfet** [comment]
Yes, it will be nice :)

**Comment by achristodoulou** [comment]
Created pull request

https://github.com/deployphp/docs/pull/52
