### ISSUE TITLE
env "bin/composer" in local:vendors, run remotely

### ISSUE THREAD

**Issue by 42antoine** [deployphp/recipes#46]
I want to report that the "bin/composer" common recipe functionality work remotely and this could be a constraint for local:vendors command execution.

I propose something like

```php
/**
 * Get composer from local system
 */
env('bin/composer', function () {
    return runLocally('which composer')->toString();
});
```

Maybe could be useful to put it in doc or directly in local recipe. What your opinion on that ?

**Comment by oanhnn** [comment]
I think why not using `localServer()` instead of local recipe ?

**Comment by elfet** [comment]
Detecting composer and other bin on local machines really complicated thing to separate some common things (mac, linux, windows, ...).
So it's better to define your own paths, like `set('local/composer', '/path/to')`

**Comment by oanhnn** [comment]
This is a bug of my PR. But i want ask: What are you think about using  a `localServer()` instead of local recipe?

I think it better, because local server has same interface with remote server.
I am always using localServer to deploy local stage.

**Comment by 42antoine** [comment]
Because i'm relatively new to the use of deployer...
If i correctly understood the use of localServer, it only did to deploy on the same computer/server you are executing the deployment, like you previously explained it @oanhnn.

In my case, i'm using local recipe to prepare deployment files : fresh project clone, composer install, npm/bower install and execute other stuff i could not execute on FTP server.

So i did the exact schema proposed in local recipe [documentation](https://github.com/deployphp/recipes/blob/master/docs/local.md).

```php
// deploy.php 

env('local_release_path', '/tmp/my_application');

/**
 * Main task
 */
task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'local:update_code',
    'local:vendors',
    'deploy:symlink',
    'cleanup',
])->desc('Deploy your project');

after('local:vendors', function() {
    upload(env('local_release_path'), env('release_path'));
})->desc('Upload local to remote');
```

In this context, i tried to add the var "local:true" to my config file deploy.yml, like follow

```yaml
prod:
  local: true
  host: domain.com
  user: www
  identity_file: ~
  stage: production
  deploy_path: /home/42antoine/www/demo
  password:
```

And i got this error, that make sense because "deploy_path" exists only on remote server.

```sh
➤ Executing task deploy:prepare
↳ on [prod]
[prod] > echo $0
[prod] < sh
[prod] < 
[prod] > if [ ! -d /home/42antoine/www/demo]; then mkdir -p /home/42antoine/www/demo; fi

Exception [Symfony\Component\Process\Exception\ProcessFailedException] on [prod] server
                                                                                                                                                                                                                                                                                                                                                                                                                               
    The command "if [ ! -d /home/42antoine/www/demo ]; then mkdir -p /home/42antoine/www/demo; fi" failed.

Exit Code: 1(General error)

Working directory: /Users/42antoine/Projects/demo/www

Output:
================


Error Output:
================
mkdir: /home/42antoine/www/demo: Permission denied
    
                                                                                                                                                                                                                                                                                                                                                                                                                               

• done on [prod]
✘ Some errors occurred!
```

@elfet, I also tried to change

```php
env('bin/composer', function () {
    return runLocally('which composer')->toString();
});
```
to 

```php
set('local/composer', '/path/to')
```

Then, it seems that the "local:vendors" tries to execute the composer install in remote server by using the {{bin/composer}} variable.

```sh
 Executing task local:vendors
↳ on [prod]
[prod] > if hash composer 2>/dev/null; then echo 'true'; fi
[prod] > readlink /home/42antoine/www/demo/release
[prod] < /home/42antoine/www/demo/releases/20160414073922
[prod] < 
[prod] > cd /home/42antoine/www/demo/releases/20160414073922 && curl -sS https://getcomposer.org/installer | php

Exception [RuntimeException] on [prod] server
                                                                                                                                                            
    X-Powered-By: PHP/4.4.9
Content-type: text/html

<br />
<b>Parse error</b>:  syntax error, unexpected T_NEW in <b>-</b> on line <b>437</b><br />
    
                                                                                                                                                            

• done on [prod]
✘ Some errors occurred!
```

**Comment by oanhnn** [comment]
I'm understanding your case included 2 steps:
1. Deploy your project to local
2. Upload you project

**Comment by oanhnn** [comment]
@42antoine I am resolved this issue by PR #48 .
Please waiting for @deployphp/maintainer merge.

**Comment by 42antoine** [comment]
👍

**Comment by johnny-bit** [comment]
Hello! #48 looks mighty fine indeed :+1:
