### ISSUE TITLE
recipes/rsync.php: got "Call to undefined method Deployer\Server\Local::getConfiguration()" using localServer(...)

### ISSUE THREAD

**Issue by nmarniesse** [deployphp/recipes#52]
As #39, rsync recipe have the same problem with localServer :  

    PHP Fatal error:  Call to undefined method Deployer\Server\Local::getConfiguration() in /root/inao/deploy/vendor/deployphp/recipes/recipes/rsync.php on line 128

Thanks

**Comment by johnny-bit** [comment]
Hi! Does the problem persist in newest tagged verision?

**Comment by nmarniesse** [comment]
Problem is fixed now. Thanks a lot!
