### ISSUE TITLE
Namepace-error when recipes are used together with deployer 4.x

### ISSUE THREAD

**Issue by mficzel** [deployphp/recipes#67]
If the recipes are used together with the deployer branch 4.x deployments fail with the message "Uncaught Error: Call to undefined function env()" 

The background is that deployer 4.x introduces the `Deployer`-namespaces in functions.php. The recipes have to be adjusted accordingly. For instance `env()` should become `\Deployer\env()`. Since this is not backwards compatible this should be done in a new branch.

**Comment by elfet** [comment]
Please show your deploy.php file.

**Comment by mficzel** [comment]
I boiled it down a bit but this is enough to get the error:

```
<?php

ini_set('display_errors', 1);

require 'recipe/common.php';
require 'vendor/deployphp/recipes/recipes/local.php';

/**
 * Read Servers from yaml file
 */
serverList('deploy-servers.yaml');

/**
 * Add
 */
task('deploy', [
    'local:prepare'
])->desc('Deployer Deployment');
```
The exact error is the following:
```
PHP Fatal error:  Uncaught Error: Call to undefined function env() in phar:///__local_directory__/deployer.phar/vendor/deployphp/recipes/recipes/local.php:13
Stack trace:
#0 __local_directory__/deploy_dbg.php(6): require()
#1 phar:///__local_directory__/deployer.phar/bin/dep(60): require('__local_directory__')
#2 /__local_directory__/deployer.phar(4): require('phar://__local_directory__')
#3 {main}
  thrown in phar:///__local_directory__/deployer.phar/vendor/deployphp/recipes/recipes/local.php on line 13
```

**Comment by mficzel** [comment]
The problem is that the method ``env()`` was moved to the ``namespace Deployer`` in the 4.x branch of deployer. So either this namespace must be used or the fullyQualyfiedName of that method ``\Deployer\env()`` must be used.

I think the easiest solution would be to add ``use \Deployer;`` to all recipes in ``deployphp/recipies`` but this would be a breaking change.

**Comment by elfet** [comment]
I think we need new version of recipes for 4.x.

**Comment by elfet** [comment]
@gordalina i'm going switch branches for main deployer repo:

* master -> 3.x
* 4.x -> master

Can you do so for recipes?
