### ISSUE TITLE
Create recipes page on deployer.org

### ISSUE THREAD

**Issue by elfet** [deployphp/recipes#8]
What about creating recipes page on deployer.org? Which will be automatically parse this repository and what main information about all recipes (task list, parameters, env vars, doc blocks). :heavy_plus_sign:  search of recipes?

**Comment by gordalina** [comment]
sounds good, do you have anything in mind to accomplish this?

**Comment by elfet** [comment]
I think there is must be route:
```php
$app->get('/recipes', function () {
    // TODO render  page
});
```
Which will be parse GitHub repositories (deployphp/recipe/*, deployphp/deployer/recipes/*) for `*.php` files with GitHub API. And parse PHP code of recipe, collecting data (task names, env vars, params) and DocBlock. And generate one page with all recipes on it.

> ## Recipe: Symfony
> ### Tasks
> ...
> ### Parameters
> ...
> ## Recipe: Laravel
> ### Tasks
> ...
> ### Parameters
> ...

**Comment by johnny-bit** [comment]
The recipes themselves have docs as required by Contributing section in readme. Why not instead of parsing php file, get markdown doc for each recipe and render it using something like Parsedown?

**Comment by ZeeCoder** [comment]
If you look at the [docs](https://github.com/deployphp/docs) repo, this is exactly what the site does.
Now I think the idea here is that now the "API" of the recipes would be available on the site, which would be generated dynamically.

I think @elfet means to keep the existing recipe documentation, since there could be a lot to explain about a recipe's usage / best practices, but it would be great to have an automatically-generated documentation from DocBlock comments, like this: http://api.symfony.com/2.0/Symfony/Component/Translation/Translator.html

**Comment by johnny-bit** [comment]
Ah, I see :)

2015-06-11 11:10 GMT+02:00 Hubert Viktor <notifications@github.com>:

> If you look at the docs <https://github.com/deployphp/docs> repo, this is
> exactly what the site does.
> Now I think the idea here is that now the "API" of the recipes would be
> available on the site, which would be generated dynamically.
>
> I think @elfet <https://github.com/elfet> means to keep the existing
> recipe documentation, since there could be a lot to explain about a
> recipe's usage / best practices, but it would be great to have an
> automatically-generated documentation from DocBlock comments, like this:
> http://api.symfony.com/2.0/Symfony/Component/Translation/Translator.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployphp/recipes/issues/8#issuecomment-111053094>.
>



-- 
Pozdrawiam,
Hubert Kowalski

**Comment by elfet** [comment]
Yeah, we need some place to collect all recipes...

...and rule them all!

**Comment by elfet** [comment]
I try to do it myself right now +)

**Comment by gordalina** [comment]
that would be awesome :smile: :beers:

**Comment by elfet** [comment]
DONE! http://deployer.org/recipes

**Comment by ZeeCoder** [comment]
Nice :+1: 
Although there's quite a few 404 errors in the Recipes table. ><

**Comment by gordalina** [comment]
good job @elfet

**Comment by elfet** [comment]
@gordalina can you rewrite README to relative links? (Like in docs)

**Comment by gordalina** [comment]
done on 968b283145f2700cb8a0074ec8dead9e72f7bdfa
