### ISSUE TITLE
slack recipe depends on stages

### ISSUE THREAD

**Issue by glensc** [deployphp/recipes#94]
given common config

```
$ deployer.phar init -t Common
Successfully created: deploy.php
$ composer require --dev deployer/recipes
```

the slack notifier throws exception:
```
                                                     
  [RuntimeException]                                 
  Configuration parameter `stages` does not exists.  
                                                     
```

**Comment by elfet** [comment]
Yes, it's better to check if it is exists. I want to refactor slack recipe a long ago.

**Comment by glensc** [comment]
do you have design doc how you want to refactor it?

**Comment by elfet** [comment]
No, i think create more useful and readable messages. Maybe have a few different styles of alerts.
