### ISSUE TITLE
recipes/newrelic.php uses runLocally to determine commit

### ISSUE THREAD

**Issue by leevigraham** [deployphp/recipes#97]
I could be wrong but it looks like recipes/newrelic.php uses runLocally to set the `newrelic_deploy_revision` and `newrelic_deploy_description`. 

* https://github.com/deployphp/recipes/blob/master/newrelic.php#L14
* https://github.com/deployphp/recipes/blob/master/newrelic.php#L17

If this is the case isn't it possible that the local machine is on a completely different branch / commit than the target commit?

**Comment by elfet** [comment]
Yes, thats possible. Need to figure out what the best solution here.

**Comment by leevigraham** [comment]
@elfet I'm looking into adding a logging task for deployments which will need the current commit. Once I figure that out I'll update the recipe with a PR.

**Comment by leevigraham** [comment]
Maybe something like:

    $git = array(
        'user' => trim(runLocally('git config user.name')),
        'revision' => trim(run('cd {{current_path}} && git log -n 1 --format="%h"')),
        'description' => trim(run('cd {{current_path}} && git log -n 1 --format="%an: %s" | tr \'"\' "\'"')),
    );

**Comment by leevigraham** [comment]
Just came across an additional issue… in the scenario where deployer is being called from a build process git config user.name might not be set. I wonder if we should use `${USER}@${HOSTNAME}` instead
